USE [master]
GO
/****** Object:  Database [LogDB]    Script Date: 15.09.2025 11:07:25 ******/
CREATE DATABASE [LogDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LogDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\LogDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LogDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\LogDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [LogDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LogDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LogDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LogDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LogDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LogDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LogDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [LogDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LogDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LogDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LogDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LogDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LogDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LogDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LogDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LogDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LogDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LogDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LogDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LogDB] SET  MULTI_USER 
GO
ALTER DATABASE [LogDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LogDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LogDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LogDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LogDB] SET QUERY_STORE = OFF
GO
USE [LogDB]
GO
/****** Object:  Table [dbo].[Item]    Script Date: 15.09.2025 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[id_item] [int] NOT NULL,
	[name] [varchar](50) NOT NULL,
	[price] [int] NOT NULL,
	[description] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 15.09.2025 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[id_login] [int] IDENTITY(1,1) NOT NULL,
	[login] [text] NOT NULL,
	[password] [varchar](50) NOT NULL,
	[id_user] [int] NOT NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[id_login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 15.09.2025 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[id_role] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](10) NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[id_role] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 15.09.2025 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[id_user] [int] IDENTITY(1,1) NOT NULL,
	[FIO] [text] NOT NULL,
	[id_role] [int] NOT NULL,
	[description] [text] NULL,
	[phone_number] [varchar](50) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[id_user] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Login]  WITH CHECK ADD  CONSTRAINT [FK_Login_User] FOREIGN KEY([id_user])
REFERENCES [dbo].[User] ([id_user])
GO
ALTER TABLE [dbo].[Login] CHECK CONSTRAINT [FK_Login_User]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Role] FOREIGN KEY([id_role])
REFERENCES [dbo].[Role] ([id_role])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Role]
GO
USE [master]
GO
ALTER DATABASE [LogDB] SET  READ_WRITE 
GO
