USE [ShopDB]
GO

CREATE TABLE [dbo].[Basket](
	[id_basket] [int] IDENTITY(1,1) NOT NULL,
	[id_user] [int] NOT NULL,
	[id_product] [int] NOT NULL,
	[count] [int] NOT NULL,
 CONSTRAINT [PK_Basket] PRIMARY KEY CLUSTERED 
(
	[id_basket] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[City](
	[id_city] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[id_city] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Login](
	[id_login] [int] IDENTITY(1,1) NOT NULL,
	[login] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[id_user] [int] NOT NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[id_login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Order](
	[id_order] [int] IDENTITY(1,1) NOT NULL,
	[is_paided] [bit] NOT NULL,
	[is_delivered] [bit] NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[id_order] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Order_list](
	[id_order_list] [int] IDENTITY(1,1) NOT NULL,
	[id_order] [int] NOT NULL,
	[id_product] [int] NOT NULL,
 CONSTRAINT [PK_Order_list_1] PRIMARY KEY CLUSTERED 
(
	[id_order_list] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Product](
	[id_product] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[price] [int] NOT NULL,
	[provider] [varchar](50) NULL,
	[image_path] [varchar](50) NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[id_product] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Role](
	[id_role] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[id_role] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Street](
	[id_street] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[id_city] [int] NOT NULL,
 CONSTRAINT [PK_Street] PRIMARY KEY CLUSTERED 
(
	[id_street] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[User](
	[id_user] [int] IDENTITY(1,1) NOT NULL,
	[surname] [varchar](50) NULL,
	[name] [varchar](50) NOT NULL,
	[desciption] [text] NULL,
	[phone] [varchar](50) NULL,
	[id_role] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[id_user] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[UserAdresses](
	[id_user_adress] [int] IDENTITY(1,1) NOT NULL,
	[id_user] [int] NOT NULL,
	[id_street] [int] NOT NULL,
	[home] [varchar](3) NOT NULL,
	[apartment] [int] NULL,
 CONSTRAINT [PK_UserAdresses] PRIMARY KEY CLUSTERED 
(
	[id_user_adress] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Basket] ADD CONSTRAINT [DF_Basket_count] DEFAULT ((0)) FOR [count]
GO

ALTER TABLE [dbo].[Basket] WITH CHECK ADD CONSTRAINT [FK_Basket_Product1] FOREIGN KEY([id_product]) REFERENCES [dbo].[Product] ([id_product]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Basket] CHECK CONSTRAINT [FK_Basket_Product1]
GO

ALTER TABLE [dbo].[Basket] WITH CHECK ADD CONSTRAINT [FK_Basket_User] FOREIGN KEY([id_user]) REFERENCES [dbo].[User] ([id_user]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Basket] CHECK CONSTRAINT [FK_Basket_User]
GO

ALTER TABLE [dbo].[Login] WITH CHECK ADD CONSTRAINT [FK_Login_User] FOREIGN KEY([id_user]) REFERENCES [dbo].[User] ([id_user]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Login] CHECK CONSTRAINT [FK_Login_User]
GO

ALTER TABLE [dbo].[Order_list] WITH CHECK ADD CONSTRAINT [FK_Order_list_Order] FOREIGN KEY([id_order]) REFERENCES [dbo].[Order] ([id_order])
GO
ALTER TABLE [dbo].[Order_list] CHECK CONSTRAINT [FK_Order_list_Order]
GO

ALTER TABLE [dbo].[Order_list] WITH CHECK ADD CONSTRAINT [FK_Order_list_Product] FOREIGN KEY([id_product]) REFERENCES [dbo].[Product] ([id_product])
GO
ALTER TABLE [dbo].[Order_list] CHECK CONSTRAINT [FK_Order_list_Product]
GO

ALTER TABLE [dbo].[Street] WITH CHECK ADD CONSTRAINT [FK_Street_City] FOREIGN KEY([id_city]) REFERENCES [dbo].[City] ([id_city]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Street] CHECK CONSTRAINT [FK_Street_City]
GO

ALTER TABLE [dbo].[User] WITH CHECK ADD CONSTRAINT [FK_User_Role] FOREIGN KEY([id_role]) REFERENCES [dbo].[Role] ([id_role]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Role]
GO

ALTER TABLE [dbo].[UserAdresses] WITH CHECK ADD CONSTRAINT [FK_UserAdresses_Street] FOREIGN KEY([id_street]) REFERENCES [dbo].[Street] ([id_street]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserAdresses] CHECK CONSTRAINT [FK_UserAdresses_Street]
GO

ALTER TABLE [dbo].[UserAdresses] WITH CHECK ADD CONSTRAINT [FK_UserAdresses_User] FOREIGN KEY([id_user]) REFERENCES [dbo].[User] ([id_user]) ON UPDATE CASCADE ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserAdresses] CHECK CONSTRAINT [FK_UserAdresses_User]
GO